spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: systemUser # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #          uri: lb://systemModel
          #          uri: http://127.0.0.1:8083
          uri: lb://systemModel
          predicates:
            - Path=/sys/** # 断言，路径相匹配的进行路由(注意**为通配符)
          filters:
            - StripPrefix=1
            - PrefixPath=/systemUser
        - id: receiver # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://receiver
          predicates:
            - Path=/receive/** # 断言，路径相匹配的进行路由(注意**为通配符)
        - id: order # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          uri: lb://order
          #          uri: http://127.0.0.1:8085
          predicates:
            - Path=/task/** # 断言，路径相匹配的进行路由(注意**为通配符)
          filters:
            - StripPrefix=1
            - PrefixPath=/order
      discovery:
        locator:
          enabled: true

server:
  port: 8091
